### ISSUE TITLE
Contributions for new contributors :)

### ISSUE THREAD

**Issue by rolandh15** [NewTuricum/Droidiqa#1]
A very interesting SDK that I am still getting to know. I already like how it is lifecycle aware.
Some things I could do quite quickly which are sort of surrounding tasks would be:
1. CI and setting up building on commit / Github releases with proper artifacts.
2. We can use https://antora.org for documentation, which should be relatively easy to set up (because I have all of this code out of the box ready to go)
3. I would actually like to write some tests for the SDK, using the test network or something similar. This would help me get to know the code, and then be able to contribute at a deeper level.
4. Id also like to build a small sample app to test the SDK integration/ show people how it might be used. Plus it gives some nice visuals for the Readme :)

Let me know what you think of my poposal.

**Comment by NewTuricum** [comment]
Sounds pretty darn good Roland! If you want, please don't hesitate and get started! Only exception might be point 4 - I already built such a wallet, it's just not on here yet. Obviously nobody is stopping you from developing your own, though...
